name: Upload To Workshop

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

concurrency:
    group: build-module
    cancel-in-progress: true

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
            - uses: m00nl1ght-dev/steam-workshop-deploy@v1
              with:
                username: ${{ secrets.STEAM_ACCOUNT_USERNAME }}
                password: ${{ secrets.STEAM_ACCOUNT_PASSWORD }}
                path: /
                appId: ${{ secrets.STEAM_APP_ID }}
                publishedFileId: ${{ secrets.STEAM_WORKSHOP_ID }}
